### ISSUE TITLE
folder name 'web3' gives error

### ISSUE THREAD

**Issue by mekhiya** [PatrickAlphaC/brownie_simple_storage#17]
Can you please explain why it gives error in first case :

**Case 1)  first created brownie project at location**
/f/web3/brownie_simple_storage 

`brownie run scripts\deploy.py`

throws error
**ModuleNotFoundError: No module named 'web3.brownie_simple_storage'**

![error-message](https://user-images.githubusercontent.com/8952786/156229355-99cdcdf4-5a7b-4fe4-9cda-316f977604c6.jpg)

**Case 2) changed name of the folder from "web3" to "web3-projects"**

 /f/web3-projects/brownie_simple_storage

`brownie run scripts\deploy.py`

ALL WORKS FINE.

I wasted so much time on this, just found this by flook.

How does naming folder name to web3, cause problem ?????

**Comment by PatrickAlphaC** [comment]
Can you please ask on the main repo? Thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
