### ISSUE TITLE
Has anyone come across the following issue?

### ISSUE THREAD

**Issue by Madgeniusblink** [PatrickAlphaC/brownie_simple_storage#2]
<img width="884" alt="Screen Shot 2021-11-15 at 7 39 42 PM" src="https://user-images.githubusercontent.com/42707764/141885865-8296a999-b0b8-4827-b2f0-c585584e156f.png">

**Comment by PatrickAlphaC** [comment]
Thanks! Tracking here... https://stackoverflow.com/questions/69970058/rpcprocesserror-unable-to-launch-local-rpc-client

Could you add any context to this question? Do you have ganache-cli installed?

**Comment by sumitdevtech** [comment]
I am getting this error after installing **ganche-cli** using **yarn** tried different ways but not able to figure out:-
**ganache-cli: command not  found**

**Comment by louisamira** [comment]
This might be useful https://stackoverflow.com/questions/70370224/problems-using-ganache-cli-command/70370260#70370260

**Comment by Dcamy** [comment]
> Thanks! Tracking here... https://stackoverflow.com/questions/69970058/rpcprocesserror-unable-to-launch-local-rpc-client
> 
> Could you add any context to this question? Do you have ganache-cli installed?

@PatrickAlphaC fyi this link has been removed

**Comment by PatrickAlphaC** [comment]
Yikes, thanks! Looks like this is the new link: https://stackoverflow.com/questions/70370224/problems-using-ganache-cli-command/70370260#70370260

**Comment by PatrickAlphaC** [comment]
Closing for now, feel free to follow up
