### ISSUE TITLE
maxFeePerGas error when running "Brownie test"

### ISSUE THREAD

**Issue by RohanNero** [PatrickAlphaC/brownie_simple_storage#21]
These are the errors I am getting after trying to run: `brownie test`
I am new to all of this so I apologize if it's an obvious solution.

ValueError: VM Exception while processing transaction: Transaction's maxFeePerGas (0) is less than the block's baseFeePerGas (104954626) (vm hf=london -> block -> tx)

FAILED tests/test_simple_storage.py::test_deploy - ValueError: VM Exception while processing transaction: Transaction's maxFeePerGas (0) is less than the block's baseFeePerGa...
FAILED tests/test_simple_storage.py::test_updating_storage - ValueError: VM Exception while processing transaction: Transaction's maxFeePerGas (0) is less than the block's ba...

**Comment by PatrickAlphaC** [comment]
Please make this issue on the larger repo, thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
