### ISSUE TITLE
.env file issues 

### ISSUE THREAD

**Issue by verystochastic** [PatrickAlphaC/brownie_simple_storage#22]
I am encountering errors in my .env file (see attached). I encounter the first error upon typing 'export' into my .env file. I am on python 3.9.7 and brownie v1.18.1. Thank you
<img width="697" alt="Screen Shot 2022-04-26 at 8 58 25 PM" src="https://user-images.githubusercontent.com/9685137/165418045-1b66a091-b48b-4dcb-a98b-e17ca9f842ca.png">

**Comment by PatrickAlphaC** [comment]
These are typescript linting issues. Something is off with your VSCode config. 

Closing for now.
