### ISSUE TITLE
No such file or directory: 'ganache-cli' Lesson 5

### ISSUE THREAD

**Issue by Bill-TheTroglodyte** [PatrickAlphaC/brownie_simple_storage#24]
Hello, at approximately 4:34:27 on Lesson 5, I have entered into my terminal on Visual Studio Code 'brownie run scripts/deploy.py' as prompted by the instructor. I get the following error after entering this information: [Errno 2] No such file or directory: 'ganache-cli'. I have properly installed ganache-cli and brownie
![Screen Shot 2022-05-03 at 2 19 05 PM](https://user-images.githubusercontent.com/100336752/166565092-619e724f-e692-49b0-a915-8c85db2fabea.png)
![Screen Shot 2022-05-03 at 2 58 45 PM](https://user-images.githubusercontent.com/100336752/166565256-09b11433-ce6b-459d-8d7a-1d51d901f90b.png)
 and have triple checked multiple times. Please help me! Thank you.

I'm using:
Python 3.10.4
node 16.15.0

**Comment by PatrickAlphaC** [comment]
Can you please make this issue here? https://github.com/smartcontractkit/full-blockchain-solidity-course-py

**Comment by Bill-TheTroglodyte** [comment]
Hello,

Thank you for your email. I am loving your course. Hopefully I can get this
resolved so I can continue. I've been stuck on it for a while. Anything you
can do to help would be greatly appreciated!

-Billy
