### ISSUE TITLE
UnboundLocalError: local variable 'account' referenced before assignment

### ISSUE THREAD

**Issue by Gwwm** [PatrickAlphaC/brownie_simple_storage#25]
cannot find the "accounts" from the brownie library. does anyone has the same problem?
<img width="410" alt="Screen Shot 2022-05-11 at 1 35 05 AM" src="https://user-images.githubusercontent.com/86285768/167688625-23ccae36-7549-42f9-9c11-57b1b8265535.png">

result:
Brownie v1.18.1 - Python development framework for Ethereum

BrownieSimpleStorageProject is the active project.
~/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/network/main.py:44: BrownieEnvironmentWarning: Development network has a block height of 2
  warnings.warn(
Attached to local RPC client listening at '127.0.0.1:8545'...

Running 'scripts/deploy.py::main'...
  File "brownie/_cli/run.py", line 51, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 11, in main
    deploy_simple_storage()
  File "./scripts/deploy.py", line 6, in deploy_simple_storage
    account = account.load("gwwm-ac")
UnboundLocalError: local variable 'account' referenced before assignment

**Comment by PatrickAlphaC** [comment]
Could you make this an issue on the full repo? Thanks!

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
