### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vedmukherjee15** [PatrickAlphaC/brownie_simple_storage#27]
Whenever I am running the code for read_value.py I am getting an Index error.
Please help me out on this

from brownie import SimpleStorage, accounts, config

def read_contract():
    simple_storage = SimpleStorage[-1]
    print(simple_storage.retrieve())

def main():
    read_contract()

@PatrickAlphaC

**Comment by PatrickAlphaC** [comment]
Could you ask on the main repo? Thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
