### ISSUE TITLE
Exception has occurred: ModuleNotFoundError

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/brownie_simple_storage#32]
Import "brownie" could not be resolved. I can not import from brownie
<img width="578" alt="Screenshot 2022-10-06 232725" src="https://user-images.githubusercontent.com/100000316/194411959-04ca270d-c691-4101-bf4c-02af86c77f8d.png">

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
