### ISSUE TITLE
 I'm not getting address shown in VS code

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/brownie_simple_storage#33]
<img width="337" alt="Screenshot 2022-10-07 233807" src="https://user-images.githubusercontent.com/100000316/194648858-47cf6efe-c537-4077-9aca-ab71a0d845f4.png">
when I type  "brownie run scripts/deploy.py" in the terminal I don't see my address, and this is my code:
from threading import activeCount
import brownie
from eth_account import account
from brownie import accounts
def deploy_simple_storage():
    account = accounts.load("freecodecamp-account")
print(account)
def main():
    deploy_simple_storage()

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py
2. Can you format your question using 3 backticks? 
Thanks!
