### ISSUE TITLE
"SimpleStorage" is unknown import symbol

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/brownie_simple_storage#34]
I have imported SimpleSorage and I have this error message:
"SimpleStorage" is unknown import symbol
and this is my code:
from brownie import accounts,config, SimpleStorage

def deploy_simple_storage():
    account = accounts[0]

#simple_storage = SimpleStorage.deploy({"from": account})
SimpleSrorage.deploy({"from": account})

print(account)

def main():
    deploy_simple_storage()

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py

thanks!
