### ISSUE TITLE
 1 passed, 3 warnings in 9.27s 

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/brownie_simple_storage#35]
when I compile my test folder it gives me this error : "1 passed, 3 warnings in 9.27s "
and this is my code:
```
from brownie import SimpleStorage, accounts


def test_deploy():

    account = accounts[0]

    simple_storage = SimpleStorage.deploy({"from": account})
    starting_value = simple_storage.retrieve()
    expected = 0

   
    assert starting_value == expected
```
<img width="722" alt="Screenshot 2022-10-22 195622" src="https://user-images.githubusercontent.com/100000316/197352762-6d89db55-5a1b-459b-9ac0-36180edb3277.png">

**Comment by PatrickAlphaC** [comment]
That's ok! Warnings are just warnings.
