### ISSUE TITLE
Brownie failing to automatically start the Ganache CLI on local development

### ISSUE THREAD

**Issue by lrodri14** [PatrickAlphaC/brownie_simple_storage#39]
When running the scripts with brownie, brownie is failing to launch ganache-cli, i'm able to use it from the UI, but doing it programmatically outputs the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'ganache-cli': 'ganache-cli'

Here are some screenshots of the console output:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/48039694/201441169-3c700b57-e3b8-4fec-864b-4becf9772cf1.png">

I decided to install to brownie in a per environment basis, didn't used pipx, however, using the pipx approach instead doesn't solve anything.

Any suggestions are welcomed.

Thank you so much!

**Comment by PatrickAlphaC** [comment]
Please make this an issue on the full repo. Thank you! 
https://github.com/smartcontractkit/full-blockchain-solidity-course-py
