### ISSUE TITLE
 environment variables 

### ISSUE THREAD

**Issue by mrogando** [PatrickAlphaC/brownie_simple_storage#4]
![image](https://user-images.githubusercontent.com/77819105/146293641-ea1a7959-929c-406d-828e-a5a37b1e1ac1.png)

The export reserved word and the variables are not showing

**Comment by mrogando** [comment]
![image](https://user-images.githubusercontent.com/77819105/146293779-151b27f8-8d81-4e1f-8350-8680c38d6150.png)

I added this account after copying and pasting from here.. and export word turned blue but, the variables still not showing up as actual variables..

**Comment by PatrickAlphaC** [comment]
In your `brownie-config.yaml` you'll need to add `dotenv: .env`

**Comment by mrogando** [comment]
That was not the problem. I figured it out already... anyways thank you so much for taking the time to answer.
