### ISSUE TITLE
Brownie installed but not importing

### ISSUE THREAD

**Issue by ghost** [PatrickAlphaC/brownie_simple_storage#40]
_Import "brownie" could not be resolved_

Hi, I have installed brownie as it shows when I type brownie --version into the terminal however when I try to import brownie it doesnt seem to be able to find it.
So far with this course, I have been struggling a lot with the environmental variables and how to create paths

Any suggestions or comments would be greatly appreciated.

**Comment by PatrickAlphaC** [comment]
Thanks for the question!

Does this help? https://stackoverflow.com/questions/70544310/import-brownie-could-not-be-resolved-in-pylance

Otherwise, could you ask on the full repo? Thanks!
https://github.com/smartcontractkit/full-blockchain-solidity-course-py
